<a href="https://colab.research.google.com/github/Aartikale23/Data_Science_Lab_SE_B_30/blob/main/Inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a 3x3 matrix (must be non-singular)
matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

# Find inverse
inverse = np.linalg.inv(matrix)

# Display results
print("Matrix:\n", matrix)
print("Inverse:\n", inverse)

Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
