<a href="https://colab.research.google.com/github/Aartikale23/Data_Science_Lab_SE_B_30/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute determinant
det = np.linalg.det(matrix)

# Display results
print("Matrix:\n", matrix)
print("Determinant:", det)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant: 0.0
